### ISSUE TITLE
broken in windows - bad escape in re.sub call

### ISSUE THREAD

**Issue by decuser** [decuser/decuser_python_playground#2]
Haven't a clue, but windows doesn't appear to be happy with:
skey = re.sub(r'^' + re.escape(srcpath), dstpath, key)

could be a problem with srcpath, dstpath, or key

python dircmp.py tests/default/src tests/default/dst

	+------------------------------------+
	|   Welcome to dircmp version 0.5.0  |
	|  Created by Will Senn on 20191210  |
	|       Last updated 20191212        |
	+------------------------------------+
	Digest: sha1
	Source (src): tests/default/src\
	Destination (dst): tests/default/dst\
	Show all files: False
	Recurse subdirectories: False

	Scanning src ... 9 files found (0.0s).
	Calculating sha1 digests in src ... done (0.0s).
	Scanning dst ... 7 files found (0.0s).
	Calculating sha1 digests in dst... done (0.0s).
	Analyzing src directory ...done (0.0s).
	Analyzing dst directory ...done (0.0s).
	Comparing src to dst ...Traceback (most recent call last):
	  File "dircmp.py", line 264, in <module>
		skey = re.sub(r'^' + re.escape(srcpath), dstpath, key)
	  File "C:\py38\lib\re.py", line 208, in sub
		return _compile(pattern, flags).sub(repl, string, count)
	  File "C:\py38\lib\re.py", line 325, in _subx
		template = _compile_repl(template, pattern)
	  File "C:\py38\lib\re.py", line 316, in _compile_repl
		return sre_parse.parse_template(repl, pattern)
	  File "C:\py38\lib\sre_parse.py", line 988, in parse_template
		this = sget()
	  File "C:\py38\lib\sre_parse.py", line 256, in get
		self.__next()
	  File "C:\py38\lib\sre_parse.py", line 245, in __next
		raise error("bad escape (end of pattern)",
	re.error: bad escape (end of pattern) at position 17

**Comment by decuser** [comment]
Oops, didn't mean to close this. Apparently, Windows has a different way of handling paths :). Ugh, the OS I love to hate. Here's what's causing the hiccup srcpath and dstpath contain extraneous characters (at least from my perspective) - the ending slash is a backslash. Gotta find a path normalization method that will handle this.
```
srcpath: tests/default/src\
dstpath: tests/default/dst\
```

**Comment by decuser** [comment]
Sheesh, complications - the above was Mingw on Windows, Cmd on Windows causes:
```
srcpath: tests\default\src\
dstpath: tests\default\dst\
```

**Comment by decuser** [comment]
Putting windows support on hold until features are stable - too much hassle to develop new feature and regression test across platforms given that I didn't do proper unit tests early on :).
