### ISSUE TITLE
Empty source dir (no non-hidden files present) causes div by zero error

### ISSUE THREAD

**Issue by decuser** [decuser/decuser_python_playground#7]
Issue with effectively empty src:

```
Calculating sha1 digests in src Traceback (most recent call last):
  File "/Users/wsenn/bin/dircmp.py", line 394, in <module>
    [src_files_dict, revidx_src_files] = calculate_sha1s(args['srcdir'], "src", src_files)
  File "/Users/wsenn/bin/dircmp.py", line 70, in calculate_sha1s
    display_progress(current_progress, src_files_bytes, 50)
  File "/Users/wsenn/bin/dircmp.py", line 165, in display_progress
    per_progress = int((total / curr) * 100)
ZeroDivisionError: division by zero

$ tree dst
dst

0 directories, 0 files
$ tree src
src
└── a

1 directory, 0 files
$ ls -a dst
.		..		.DS_Store	.DS_Store.o
$ ls -a src
.	..	a
$ ls -a src/a
.		..		.empty		.emptytoo
$ 
```

**Comment by decuser** [comment]
actually, it's when the filesize is zero! doh! fix is on the horizon.

**Comment by decuser** [comment]
Confirmed working.
